
@startuml

!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/materia-outline/puml-theme-materia-outline.puml

participant "API" as API
participant "service" as service
database "database" as DB

autonumber
activate API
  API -> service: [call API create pin {title, desciption}]

  activate service
    service -> service: [validate title, description, boardName, pictureList]


  group ref
        service -> service: call API create board
  end
  deactivate service


    service -> DB: [insert new pin]
    activate service

    activate DB
    DB -> service: [add picture/video(s) for pin]
    activate service
      group ref [add picture/video(s) in list]
       service -> service: [call API add picture]
    end
  deactivate service
    DB --> service: [finish]
    deactivate DB
    service --> API: [return a new pin]
  deactivate service



deactivate API
@enduml


